TRANSLATION_SERVICE_YANDEX = 'yandex'
TRANSLATION_SERVICE_GOOGLE = 'google'
TRANSLATION_SERVICE_BING = 'bing'
TRANSLATION_SERVICE_DEEPL = 'deepl'

TRANSLATOR_BY_SERVICE_NAME = [
    TRANSLATION_SERVICE_YANDEX,
    TRANSLATION_SERVICE_GOOGLE,
    TRANSLATION_SERVICE_BING,
    TRANSLATION_SERVICE_DEEPL,
]
